### ISSUE TITLE
Can not npm run build without manually saving 'polka' and 'compression' to package.json

### ISSUE THREAD

**Issue by JU12000** [HalfdanJ/svelte-adapter-appengine#10]
Steps to reproduce:

1. Using pnpm run `pnpm install --save-dev svelte-adapter-appengine`
2. Add the adapter to svelte.config.js per the instructions
3. `npm run build`. The following error messages are received.

`> .svelte-kit/appengine-tmp/entry.js:1:18: error: Could not resolve "polka" (mark it as external to exclude it from the bundle)`
`> .svelte-kit/appengine-tmp/entry.js:2:24: error: Could not resolve "compression" (mark it as external to exclude it from the bundle)`

I was able to get around this by just running `pnpm install --save-dev polka compression` and it worked fine, but It does increase my package size and it's likely worth documenting/looking into.

Thanks for writing this though I really wasn't looking forward to tackling this myself :).

**Comment by HalfdanJ** [comment]
I don't have any experience (yet) with pnpm. Both polka and compression are listed as dependencies in the package.json file, so not sure why pnpm doesn't install them? Do you have any experience with that? 

The two packages are only imported by the node server, so it shouldn't increase the bundle size of the clientside code.

**Comment by JU12000** [comment]
So I did some further research with this and it seems like it's an issue with Rollup not being Node-compliant in the way it forms it's dependency tree. I'm not sure why it only showed up with your package and nothing else so far but I'm going to go ahead and open an issue with them instead.

As for the increased bundle size, I was just doing my math wrong. Thanks for the quick reply!
