### ISSUE TITLE
Failed to fetch dynamically imported module _app/undefined

### ISSUE THREAD

**Issue by david-bergman** [HalfdanJ/svelte-adapter-appengine#11]
Once deployed as an app to google cloud, I get this error on page load, or on refreshing the browser. 

Failed to fetch dynamically imported module: https://xxxxx.ew.r.appspot.com/_app/undefined

it seems to happen as a result of an extra item inserted into the nodes array - import("/_app/undefined") when hydrating a page as below

![image](https://user-images.githubusercontent.com/13984154/149484893-9f4c9338-1e5f-4d0f-8a3c-bf07deea4643.png)

Seems to relate to a similar issue across other cloud providers (see issue with vercel below)

https://github.com/sveltejs/kit/issues/3308

As soon as I use page links, ie. by clicking on links within the pages (not refreshing the browser) everything functions and navigates as expected.

**Comment by david-bergman** [comment]
issue seems sporadic, I am going to close it until I use it more ...

**Comment by HalfdanJ** [comment]
Hmm I've also seen this error myself once, and it then disappeared before I could debug it.

**Comment by HalfdanJ** [comment]
Since the same happens in other adapters, it leaves me to think it's a bug in the new adapter API.

**Comment by david-bergman** [comment]
I thought maybe its the version of node I was using to run the build ? I was using v14.16.1 , I tried v16.0.0 as well, same result once deployed... 

pretty consistent error for me now _app/undefined - Failed to fetch dynamically imported module

**Comment by david-bergman** [comment]
I am just going to reopen, in case the possible bug in the adapter api is helped by this... 

![image](https://user-images.githubusercontent.com/13984154/149721119-f853caa5-eac1-4002-83bb-51676f3a20e0.png)

**Comment by HalfdanJ** [comment]
Any chance you can share some  steps to reproduce?

**Comment by david-bergman** [comment]
this seemed to have been caused by this library (https://github.com/zerodevx/svelte-toast), once removed I no longer able to reproduce the error
