### ISSUE TITLE
app.yaml backslashes (Windows)

### ISSUE THREAD

**Issue by Joonel** [HalfdanJ/svelte-adapter-appengine#115]
Hello!
How to deal with these backslashes? It worked earlier (deployed to gcloud), but now it is not...

![image](https://github.com/HalfdanJ/svelte-adapter-appengine/assets/69682842/7bac3c52-306a-4d15-90e4-5476d575ea4d)

**Comment by Joonel** [comment]
Yeah, I managed to replace them with normal ones by simple editing, but anyway.

**Comment by HalfdanJ** [comment]
Yeah I noticed that a release of sveltekit introduced a problem in the adapter (a test started failing on just windows after a new sveltekit release). I haven't gotten around to fixing it in the lib yet, but PRS are very welcome.

**Comment by HalfdanJ** [comment]
This seems to have been solved by itself upstream in sveltekit itself
