### ISSUE TITLE
Update to support SvelteKit 2.0

### ISSUE THREAD

**Issue by randomiser** [HalfdanJ/svelte-adapter-appengine#140]
With Sveltekit 2.0 now released it would be great to update this to support it.

https://svelte.dev/blog/sveltekit-2

**Comment by Dabugger** [comment]
> With Sveltekit 2.0 now released it would be great to update this to support it.
> 
> https://svelte.dev/blog/sveltekit-2

Yes, we need sveltekit 2 support.

**Comment by HalfdanJ** [comment]
I will not be able to work on this until the new year, but anyone can work on a PR I will happily make a release

**Comment by Dabugger** [comment]
> I will not be able to work on this until the new year, but anyone can work on a PR I will happily make a release

how can we know what files to modify, what is the first step?

**Comment by HalfdanJ** [comment]
I haven't myself yet tried to migrate a project with the adapter to V2, so don't know what might be needed. I assume the ticket got opened because something isn't working?

**Comment by Dabugger** [comment]
> I haven't myself yet tried to migrate a project with the adapter to V2, so don't know what might be needed. I assume the ticket got opened because something isn't working?

Yes, your adapter is not working with sveltekit 2, there is an error regarding the build folder, i believe it changed with sveltekit 2.

**Comment by mjoycemilburn** [comment]
Issues I've noticed include:

1. sveltekit v2 requires you to  import vitePreprocess from @sveltejs/vite-plugin-svelte not @sveltejs/kit/vite 
2. cloud Run support for nodejsRuntime: 16 will cease in Jan '24
3. the demo app at https://svelte-demo-329602.uc.r.appspot.com/ no longer works

Additionally, svelte-adapter-appengine worked great for me in a test webap at sveltekit v1.27.4 but, since I moved to 2.0.0, deployments to app engine fail with an "Invalid request body" error. 

I'm still investigating  the issue - most likely a problem at my end, so please don't get discouraged. This library has enormous potential.

**Comment by HalfdanJ** [comment]
Thanks @mjoycemilburn for the list. 

1.  This seems to only be a README change, not actually requiring any changes to the adapter itself. 
2. Changing the default nodejs runtime to v18 now: #145 
3. Thanks for pointing out the url was dead. Didn't have anything to do with sveltekit 2, the project had just been deleted by accident. [Deployed again](https://svelte-adapter-demo.uc.r.appspot.com/) #146

The demo app works fine with sveltekit 2.0. If you are able to identify any other issues with the adapter and v2, please re-open this issue.

**Comment by mjoycemilburn** [comment]
Hi Jonas,

Thanks for picking up my comments. Great to find you back on the case (if
also slightly disturbing to note that you hadn't anything better to do on
New Year's Day!). But this stuff is all super-exciting, so
you're easily forgiven.

As I said, I'm very new to Svelte, so my "Invalid request body" with a v2
build is almost certainly down to my own incompetence. I'll be working on
my project over the next few weeks so will update you shortly.

In the meantime, a Happy (and, I trust, well-paid) New Year to you.

With best wishes, MartinJ
