### ISSUE TITLE
Error on generated `package.json`: unmarshalling package.json

### ISSUE THREAD

**Issue by DanielRios549** [HalfdanJ/svelte-adapter-appengine#184]
I've got the followwing error when deploy the app:
`status: FAILURE
unmarshalling package.json: json: cannot unmarshal array into Go struct field PackageJSON.dependencies of type map[string]string`

The generated `package.json` is set to an empty array in `dependencies`, when changed to an empty object it works.

Before: 
```json
  {
    "type": "commonjs",
    "dependencies": []
  }
```

After:
```json
  {
    "type": "commonjs",
    "dependencies": {}
  }
```

**Comment by HalfdanJ** [comment]
Few questions 
- which version of nodejs are you on
- which os are you using 
- are you providing any configuration to the adapter?

**Comment by DanielRios549** [comment]
I just figured out what was causing this: An empty array on adapter dependencies configuration in `svelte.config.js`. Just remove it and everything works as expected.
