### ISSUE TITLE
"Invalid request body" error when running on Google App Engine

### ISSUE THREAD

**Issue by vdelacerda** [HalfdanJ/svelte-adapter-appengine#49]
When running the app on Google App Engine, I have the error "Invalid Request Body".
I am using the last version of Sveltekit.

The log for the build :

backoffice@0.0.1 build
vite build

vite v3.1.0 building for production...
✓ 30 modules transformed.
vite v3.1.0 building SSR bundle for production...
✓ 44 modules transformed.
Generated an empty chunk: "hooks"
.svelte-kit/output/server/vite-manifest.json                                  1.29 KiB
.svelte-kit/output/server/index.js                                            67.80 KiB
.svelte-kit/output/server/entries/endpoints/api/notifications/_server.ts.js   0.07 KiB
.svelte-kit/output/server/entries/fallbacks/layout.svelte.js                  0.23 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js                   1.50 KiB
.svelte-kit/output/server/entries/pages/_page.svelte.js                       0.31 KiB
.svelte-kit/output/server/chunks/index.js                                     3.10 KiB
.svelte-kit/output/server/chunks/hooks.js                                     0.00 KiB

Run npm run preview to preview your production build locally.
.svelte-kit/output/client/vite-manifest.json                                         2.21 KiB
.svelte-kit/output/client/_app/immutable/components/layout.svelte-34b45f3a.js        0.53 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/immutable/components/error.svelte-ea5211a3.js         2.07 KiB / gzip: 0.95 KiB
.svelte-kit/output/client/_app/immutable/components/pages/_page.svelte-9e7c726b.js   0.81 KiB / gzip: 0.47 KiB
.svelte-kit/output/client/_app/immutable/chunks/singletons-d21fa692.js               1.81 KiB / gzip: 0.99 KiB
.svelte-kit/output/client/_app/immutable/start-b228e340.js                           22.92 KiB / gzip: 8.99 KiB
.svelte-kit/output/client/_app/immutable/chunks/0-3f4b2ff7.js                        0.09 KiB / gzip: 0.09 KiB
.svelte-kit/output/client/_app/immutable/chunks/1-253c57f3.js                        0.09 KiB / gzip: 0.09 KiB
.svelte-kit/output/client/_app/immutable/chunks/2-fdf0651a.js                        0.09 KiB / gzip: 0.10 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-4f5b2732.js                    6.62 KiB / gzip: 2.70 KiB

And the log of the deployment :

Services to deploy:

descriptor:                  [/home/virgile/Projets/bodela/sources/motard_way/backoffice/build/app.yaml]
source:                      [/home/virgile/Projets/bodela/sources/motard_way/backoffice/build]
target project:              [motard-book]
target service:              [default]
target version:              [20220910t113338]
target url:                  [https://motard-book.nw.r.appspot.com]
target service account:      [App Engine default service account]

Do you want to continue (Y/n)?  Y

Beginning deployment of service [default]...
Created .gcloudignore file. See `gcloud topic gcloudignore` for details.
╔════════════════════════════════════════════════════════════╗
╠═ Uploading 9 files to Google Cloud Storage                ═╣
╚════════════════════════════════════════════════════════════╝
File upload done.
Updating service [default]...⠛WARNING: *** Improve build performance by generating and committing package-lock.json.                                                    

Updating service [default]...done.                                                                                                                                      
Setting traffic split for service [default]...done.                                                                                                                     
Deployed service [default] to [https://motard-book.nw.r.appspot.com]

You can stream logs from the command line by running:
  $ gcloud app logs tail -s default

To view your application in the web browser run:
  $ gcloud app browse

**Comment by maumarteau** [comment]
Same error here!

**Comment by kempermi** [comment]
I am getting the same error

**Comment by HalfdanJ** [comment]
Should now be fixed in `0.9.1 `

**Comment by jameslounds** [comment]
does not work for me in `0.9.1`. Same error

**Comment by HalfdanJ** [comment]
Which version of sveltekit?

**Comment by jameslounds** [comment]
package.json
```json
{
    "@sveltejs/kit": "^1.0.0-next.471",
    "svelte": "^3.44.0",
    "svelte-adapter-appengine": "^0.9.1"
}
```

**Comment by jameslounds** [comment]
yep, all I needed to do was update 🤦 

sorry to waste your time,. this is working for me with

`package.json`
```json
{
	"@sveltejs/kit": "^1.0.0-next.506",
	"svelte": "^3.44.0",
	"svelte-adapter-appengine": "^0.9.1",
}
```
