### ISSUE TITLE
App defaults http instead of https on App Engine

### ISSUE THREAD

**Issue by lewiseman** [HalfdanJ/svelte-adapter-appengine#50]
Despite having the secure:always , the app resolves to use the unsecure http rather than https .

Although adding secure to all the urls fixes it . As shown below :

`handlers:
  - url: //?$
    secure: always
    static_files: storage/index.html
    upload: storage/index.html
  - url: /about/?$
    secure: always
    static_files: storage/about.html
    upload: storage/about.html
  - url: /_app/immutable/
    secure: always
    static_dir: storage/_app/immutable
    expiration: 30d 0h
  - url: /_app/
    secure: always
    static_dir: storage/_app
  - url: /.*
    secure: always
    script: auto`

**Comment by HalfdanJ** [comment]
I have not experienced this myself. 
Are you using appengine flex, or custom domain by any chance? 

Can you try following: 

secure: always
redirect_http_response_code: 301

**Comment by HalfdanJ** [comment]
Haven't read about this before, but maybe this header needs to get added to the adapter 

https://cloud.google.com/appengine/docs/standard/nodejs/how-requests-are-handled#forcing_https_connections

**Comment by lewiseman** [comment]
> 

I am using appengine standard and yes a custom domain . The normal default appengine domain works well .

**Comment by HalfdanJ** [comment]
I dont have a ton of experience with custom domains. But did you setup ssl certificate? Also, does the https endpoint work if you force it there in the browser?

**Comment by lewiseman** [comment]
Appengine custom domain provides automatic ssl for the domains added. 
When you force the site to https custom domain it works too . But when you enter a url like www.example.com it defaults to the insecure http .

The header you mentioned will be a great addition. But only works after the browser has detected https previously.

**Comment by HalfdanJ** [comment]
Are you sure? I can't find a reference to that

**Comment by lewiseman** [comment]
Here is a reference 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security 
Its explained as a note .
