### ISSUE TITLE
Static files in the app.yaml when building

### ISSUE THREAD

**Issue by kgoldthorpe** [HalfdanJ/svelte-adapter-appengine#82]
Under the source directory in my Svelte project, I have a "static" folder containing images.  Build adds the following lines to the app.yaml for each image file.  These break the GCP deployment.  By deleting these lines everything works as expected.
url: /fifthimage.jpg
    static_files: storage\fifthimage.jpg
    upload: storage\fifthimage.jpg
    secure: always

**Comment by HalfdanJ** [comment]
Based on the `\` character, i'm guessing you maybe are on windows? Could you try and change the characters to `/` and see if that fixes it, if so it will be an easy fix in the adapter
